### ISSUE TITLE
Error messages are not written to stderr

### ISSUE THREAD

**Issue by EmilySeville7cfg** [Dragon-0609/Yuki-Theme#4]
**Describe the bug**

Several error messages are [not written](https://github.com/Dragon-0609/Yuki-Theme/blob/main/Yuki%20Installer/Program.cs#L27) to stderr.

**Expected behavior**

Error messages are written to stderr.

**Comment by Dragon-0609** [comment]
Thanks. I didn't spent much time to explain the user what is happening. Everything was done fast, so I thought it isn't necessary to let the user read errors. Now, if there's some errors, it will show.
