### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dartyk-github** [Dragon-0609/Yuki-Theme#45]
**Describe the bug**
Плагин не работает после установки, даже метод программы не работает: "yuki_theme.exe" не запускается.
NET.Framework 4.8 установлен. Других несостыковок я не вижу. Помогите пожалуйста с проблемой. Очень надоел белый паскаль.

**Desktop **
 - Windows 10 version 1607

**Comment by Dragon-0609** [comment]
Попробуйте запустить "Yuki_Theme.exe" из этого архива:
https://drive.google.com/file/d/1yxAhmq4vG9by7b6NEwcNEgZOcNgyb-4d/view?usp=sharing

**Comment by dartyk-github** [comment]
[yuki.log](https://github.com/Dragon-0609/Yuki-Theme/files/11054381/yuki.log)
При запуске, все нормально, но после попытки импортировать тему - ошибка.

**Comment by dartyk-github** [comment]
Запустив от имени администратора, все нормально работает. В файле yuki.log ничего нет.

**Comment by Dragon-0609** [comment]
> Запустив от имени администратора, все нормально работает. В файле yuki.log ничего нет.

хорошо. В последних изменениях я добавил фичу, которая спрашивает права администратора при открытии программы и плагина.

Программу можно только открыть с правами админа, а плагин можно и открыть без прав, но возможно не сможет сменить тему если Pascal находится в Program Files.

Я планирую в ближайшее время доработать и выпустить бета версию. В нём баг будет исправлен.

**Comment by dartyk-github** [comment]
Ваш файл который вы мне отправили работает, а другие нет, даже с правами администратора. Вы меня походу не правильно поняли

**Comment by Dragon-0609** [comment]
> Ваш файл который вы мне отправили работает, а другие нет, даже с правами администратора. Вы меня походу не правильно поняли

Вы проверяли эту версию: [бета 8-ой версии](https://github.com/Dragon-0609/Yuki-Theme/releases/tag/v8.0.0-beta) и эту: [7-я версия](https://github.com/Dragon-0609/Yuki-Theme/releases/tag/v7.0.0)?

Файл который я отправил тот же и что бета 8-ой версии. Только я добавил логгер, который записивает все ошибки в файл.

**Comment by Dragon-0609** [comment]
А плагин всё ещё не работает?

**Comment by dartyk-github** [comment]
Плагин до сих пор не работает.

**Comment by Dragon-0609** [comment]
Какая версия Pascal у вас?

**Comment by dartyk-github** [comment]
У меня PascalABC.NET 3.8.3, я подозреваю что проблема именно в версии. Но я не нашел в просторах интернета предыдущие версии.

**Comment by Dragon-0609** [comment]
> У меня PascalABC.NET 3.8.3, я подозреваю что проблема именно в версии. Но я не нашел в просторах интернета предыдущие версии.

У меня тоже 3.8.3.  Дело не в версии. 

Если честно, я не знаю почему не работает. 

Даже после того как вы скопировали с Yuki_Theme_Plugin.zip в папку Pascal, редактор не открывается, или же не видно что плагин работает?

**Comment by dartyk-github** [comment]
Редактор открывается, но нет признаков работы плагина

**Comment by Dragon-0609** [comment]
Можете отправить скриншот окна `О программе` с списком плагинов как тут:

![screenshot_1](https://drive.google.com/uc?export=view&id=1Wfglbd4Hxv0CmVZ4u4oFCOM78WtFH30J)

![screenshot_2](https://drive.google.com/uc?export=view&id=1JdLoOeP5SKYBO-UR6kt81Uw3wYDwoYkW)

А ещё список файлов папки Pascal, как тут:
![screenshot_2](https://drive.google.com/uc?export=view&id=14NfKfKWp00AcA6FXf4hpR1PdhAbPqfIJ)

**Comment by dartyk-github** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/128614489/227768288-244a99a9-1cfc-47fd-9b72-7fa5d213cc6b.png)
![Screenshot_2](https://user-images.githubusercontent.com/128614489/227768292-891004b6-f4d2-4789-8007-970ce151a5c8.png)
![Screenshot_3](https://user-images.githubusercontent.com/128614489/227768294-31ceb63c-69af-4420-a57a-fcd44f91331c.png)
![Screenshot_4](https://user-images.githubusercontent.com/128614489/227768295-b3c9f627-a6e9-45b5-a9bb-7b42a1e146b1.png)
![Screenshot_5](https://user-images.githubusercontent.com/128614489/227768296-a81fbbfd-4b93-4c79-9518-2565857e0427.png)
Вот весь список

**Comment by Dragon-0609** [comment]
Хмм... файлы на месте. Но почему-то редактор не может загрузить плагин. 

Попробуйте использовать сборку где я отключил все функции кроме самых базовых (фон, стикер). 
Для этого скачайте и замените [версией 7](https://github.com/Dragon-0609/Yuki-Theme/releases/download/v7.0.0/Yuki_Theme_Plugin.zip).

После этого этим файлом:
https://drive.google.com/file/d/1VWHmm_seFvgh_4ceML9fh_wwI4i-Y4cA/view?usp=sharing

**Comment by dartyk-github** [comment]
Сделал все так как вы сказали, и все равно Pascal не видит плагин

**Comment by Dragon-0609** [comment]
Тогда не знаю из-за чего плагин не работает.

Подумаю, что можно сделать, чтобы редактор находил плагин

**Comment by dartyk-github** [comment]
Недавно установил windows 11, и решил попробовать установить плагин, в итоге все отлично работает.
