### ISSUE TITLE
can you help me?(i can't do anything with it, but i tried to reinstall) можете помочь мне?(я не могу ничего с этим поделать, я даже пытался переустановить паскаль)

### ISSUE THREAD

**Issue by tyman123qwerty** [Dragon-0609/Yuki-Theme#46]
![image](https://user-images.githubusercontent.com/132219777/235365488-713375a1-5d00-465d-9eac-cb02697cf9cc.png)

**Comment by Dragon-0609** [comment]
Откройте Pascal ABC.NET с правами администратора

**Comment by tyman123qwerty** [comment]
попробую, спасибо

**Comment by tyman123qwerty** [comment]
не работает(
![image](https://user-images.githubusercontent.com/132219777/235366269-c3b3a815-e9f2-4705-8c1a-d20260f15ce3.png)

**Comment by tyman123qwerty** [comment]
о, заработало
