### ISSUE TITLE
Не работает плагин

### ISSUE THREAD

**Issue by DimaPO404** [Dragon-0609/Yuki-Theme#53]
После распаковки плагина в папку с паскалем и после запуска самого паскаля ничего не происходит, просто открывается обычный паскаль и всё, никаких модулей не добавляется.

**Comment by Dragon-0609** [comment]
Какая версия Windows у вас? 
Насколько я знаю плагин не работает в Windows 11.

**Comment by DimaPO404** [comment]
У меня Window 10, плагин проверял на версии паскаля 8.9.2 и 8.9

**Comment by Dragon-0609** [comment]
Насколько я знаю в PascalABC.NET пока нету 8.9.2 и 8.9 версии. 
В официальком сайте есть `PascalABC.NET (version 3.9.0, build 3307 dated 07/10/2023) - Windows, Linux`. Вы уверену что написали правильно?

**Comment by DimaPO404** [comment]
Да, я ошибся, я пробовал на версии 3.8.2 и 3.9

**Comment by Dragon-0609** [comment]
Попробуйте использовать старые версии плагина. Если и те не работают, вы можете использовать программу. С ней вы сможете применить тему только для редактора

**Comment by exdsr** [comment]
Здравствуйте! У меня немного иная проблема. Плагин стартует, но не может применится ни одна тема
![errors1](https://github.com/user-attachments/assets/88c89145-2f9b-4fbd-b383-c3f0f06f3ec9)
![errors2](https://github.com/user-attachments/assets/e1840150-efb4-496a-9086-62ae4c7f91f3)
ОС: Windows 11

**Comment by Dragon-0609** [comment]
Здравствуйте. Проблема в том что плагину нужны права администратора для изменения темы (нужен доступ к Program Files который можно менять только с правами админа).
Запустите PascalABC.NET c правами администратора.
