### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yaOuris** [Dragon-0609/Yuki-Theme#54]
**Не могу пользоваться плагином**
не могу никаким способом начать пользоваться плагином, возможно проблема решается в 2 клика, но все же прошу помочь

**Ошибка**

1. Захожу в паскаль
2. Захожу в 'модули', а дальше в Yuki Theme
3. Кликаю на 'Switch Theme ' и пытаюсь поменять на любую тему, что выдает ошибку

!(http://prntscr.com/5u9D-9fIRwT1) 

P.S. у меня ссылка на скриншот открылась только с впн

**Comment by Dragon-0609** [comment]
Какая версия плагина вы используете?

Нужно запустить Паскаль с правами администратора

**Comment by yaOuris** [comment]
хах, запуск  с правами администратора помог, спасибо большое
