### ISSUE TITLE
Не могу открыть файл yuki_theme.exe

### ISSUE THREAD

**Issue by m0zzileroy** [Dragon-0609/Yuki-Theme#56]
Ошибка :
Я извлёк все файлы из .zip в PascalABC.NET, открыл .exe, но ничего не происходит, только показывает что компьютер чем-то занят(у курсора знак загрузки)

Ожидания :
Я ожидал что программа откроется и я смогу изменить стиль и тему интерфейса в PascalABC.

ОС :
Windows 11 Домашняя

Подробности :
После того как yuki_theme.exe не запустился, я решил опять заняться своим проектом, но он крашнулся, я посмотрел отчёт и там оказалось то что .dll файлы (насколько я понимаю) были повреждены. Моё предположение то, что версия паскаля может не совпадать с версией yuki_theme, скорее всего она была написана для более поздней версии. Конечно хотелось бы что бы автор выпустил юки на новую версию)

**Comment by SuhanOnki** [comment]
Какую версию PascalABC.NET вы используете?
Рекомендую использовать последнюю версию паскалья. Если ошибка всё ещё выходит, тогда удалите dll с названием Yuki Theme.

**Comment by Dragon-0609** [comment]
Какую версию PascalABC.NET вы используете?
Рекомендую использовать последнюю версию паскалья. Если ошибка всё ещё выходит, тогда удалите dll с названием Yuki Theme.

**Comment by m0zzileroy** [comment]
Я нашёл 3 файла под названием : Yuiki Theme.Core.dll | Yuki Theme.Themes.dll | Yuki Theme Plugin.dll. (я извлёк файлы из .zip файла плагина, но сочетание клавиш ctrl + ` не работает).

**Comment by Dragon-0609** [comment]
Вы скачали Yuki Theme Plugin?
yuki_theme.exe это версия программы. Для Pascal ABC.NET нужно поставить версию плагина

**Comment by m0zzileroy** [comment]
Сейчас я извлёк в папку PascalABC.NET плагин yuki но перезапустив паскаль, комбинация кнопок не сработала

**Comment by Dragon-0609** [comment]
Посмотрите в вкладке Модули в окне PascalABC.NET. Если там нет Yuki Theme, тогда по некоторым причинам плагин не работает
как тут: ![image](https://github.com/Dragon-0609/Yuki-Theme/assets/80271099/d67a9ac6-d060-4002-aa75-587a31753bdd)

**Comment by m0zzileroy** [comment]
Хорошо, сейчас посмотрю

**Comment by m0zzileroy** [comment]
Нету(

**Comment by Dragon-0609** [comment]
Тогда не плагин не установился.
Можно через 5 часов связаться со мной по почте?
reddragon.levelup@gmail.com

C вашего согласия я хочу помочь с установкой и использованием плагина через программу AnyDesk. Можете прочитать что такое AnyDesk в интернете

**Comment by m0zzileroy** [comment]
Я уезжаю на дачу и буду дома наверно к 11 часам

**Comment by Dragon-0609** [comment]
через сколько часов сможете связаться?

**Comment by m0zzileroy** [comment]
скорее всего возможно даже завтра

**Comment by m0zzileroy** [comment]
или постараюсь взять с собой ноут

**Comment by Dragon-0609** [comment]
Ок

**Comment by m0zzileroy** [comment]
если вы завтра сможете, то я не занят почти весь день

**Comment by Dragon-0609** [comment]
Напишите мне, тогда я отвечу через сколько времени буду свободен

**Comment by m0zzileroy** [comment]
хорошо, доброго вечера вам

**Comment by Dragon-0609** [comment]
И вам

**Comment by m0zzileroy** [comment]
Здравствуйте, вы сейчас можете?

**Comment by Dragon-0609** [comment]
Здравствуйте, да, сейчас могу

**Comment by m0zzileroy** [comment]
Я установил на свой пк щас yuki_theme (plugin) и всё заработало, не знаю что за ошибка была на ноуте. Спасибо большое за такой прекрасный плагин!)
